services:

  retdec:
    image: remnux/retdec
    volumes:
      - ./sessions:/sessions

  vectordb:
    image: qdrant/qdrant
    container_name: vectordb
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - backend

  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    runtime: nvidia
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./models:/root/.ollama/models
    entrypoint: ["ollama", "serve"]
    networks:
      - backend

networks:
  backend:

volumes:
  ollama:
  qdrant-data:
