services:

  analyzer:
    image: remnux/retdec
    volumes:
      - ./sessions:/sessions

  indexer:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - backend

  embedder:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    runtime: nvidia
    environment:
      - OLLAMA_LLM_LIBRARY=cuda
      - OLLAMA_LOAD_TIMEOUT=10m
      - OLLAMA_KEEP_ALIVE=30m
      - OLLAMA_NUM_PARALLEL=1
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./models:/root/.ollama/models
    entrypoint: ["ollama", "serve"]
    networks:
      - backend

  talker:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    runtime: nvidia
    environment:
      - OLLAMA_LLM_LIBRARY=cuda
      - OLLAMA_LOAD_TIMEOUT=10m
      - OLLAMA_KEEP_ALIVE=30m
      - OLLAMA_NUM_PARALLEL=1
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
      - ./models:/root/.ollama/models
    entrypoint: ["ollama", "serve"]
    networks:
      - backend

networks:
  backend:

volumes:
  ollama:
  qdrant-data:
