services:

  disassembler:
    image: remnux/retdec
    volumes:
      - ./sessions:/sessions

  vector-db:
    image: qdrant/qdrant
    container_name: vector-db
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - backend

  embedder:
    image: ollama/ollama
    container_name: embedder
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    runtime: nvidia
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./models:/root/.ollama/models
    entrypoint: ["ollama", "serve"]
    networks:
      - backend

  llm-server:
    image: ollama/ollama
    container_name: llm-server
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    runtime: nvidia
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
      - ./models:/root/.ollama/models
    entrypoint: ["ollama", "serve"]
    networks:
      - backend

networks:
  backend:

volumes:
  ollama:
  qdrant-data:
