
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

namespace Refract.CLI.Views;

public partial class TopLevelView {
    public TopLevelView() {
        InitializeComponent();

        // Finalize views
        asmTextView.ReadOnly = true;
        asmTextView.CanFocus = true;
        asmTextView.WordWrap = false;
        asmTextView.VerticalScrollBar.Visible = true;
        asmTextView.VerticalScrollBar.AutoShow = true;
        asmTextView.HorizontalScrollBar.Visible = true;
        asmTextView.HorizontalScrollBar.AutoShow = true;
        
        cTextView.ReadOnly = true;
        cTextView.CanFocus = true;
        cTextView.WordWrap = false;
        cTextView.VerticalScrollBar.Visible = true;
        cTextView.VerticalScrollBar.AutoShow = true;
        cTextView.HorizontalScrollBar.Visible = true;
        cTextView.HorizontalScrollBar.AutoShow = true;
        
        // Set event handlers
        askInput.Accepting += (_, _) =>
        {
            askInput.Text = "";
        };
    }

    public void SetAsm(string asm)
    {
        asmTextView.Text = asm;
    }

    public void SetC(string c)
    {
        cTextView.Text = c;
    }
}