
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Refract.CLI.Views {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class TopLevelView : Terminal.Gui.Views.Toplevel {
        
        private Terminal.Gui.Views.FrameView asmView;
        
        private Terminal.Gui.Views.TextView asmTextView;
        
        private Terminal.Gui.Views.FrameView cView;
        
        private Terminal.Gui.Views.TextView cTextView;
        
        private Terminal.Gui.Views.FrameView outputView;
        
        private Terminal.Gui.Views.FrameView askView;
        
        private Terminal.Gui.Views.TextView askInput;
        
        private void InitializeComponent() {
            this.askInput = new Terminal.Gui.Views.TextView();
            this.askView = new Terminal.Gui.Views.FrameView();
            this.outputView = new Terminal.Gui.Views.FrameView();
            this.cTextView = new Terminal.Gui.Views.TextView();
            this.cView = new Terminal.Gui.Views.FrameView();
            this.asmTextView = new Terminal.Gui.Views.TextView();
            this.asmView = new Terminal.Gui.Views.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.asmView.Width = Dim.Percent(33);
            this.asmView.Height = Dim.Fill(0);
            this.asmView.X = 0;
            this.asmView.Y = 0;
            this.asmView.Visible = true;
            this.asmView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.asmView.CanFocus = true;
            this.asmView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.asmView.Data = "asmView";
            this.asmView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.asmView.Title = "ASM";
            this.Add(this.asmView);
            this.asmTextView.Width = Dim.Percent(100);
            this.asmTextView.Height = Dim.Percent(100);
            this.asmTextView.X = 0;
            this.asmTextView.Y = 0;
            this.asmTextView.Visible = true;
            this.asmTextView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.asmTextView.CanFocus = false;
            this.asmTextView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.asmTextView.AllowsTab = true;
            this.asmTextView.AllowsReturn = true;
            this.asmTextView.WordWrap = true;
            this.asmTextView.Data = "asmTextView";
            this.asmTextView.Text = "";
            this.asmTextView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.asmView.Add(this.asmTextView);
            this.cView.Width = Dim.Percent(33);
            this.cView.Height = Dim.Percent(100);
            this.cView.X = Pos.Percent(33);
            this.cView.Y = 0;
            this.cView.Visible = true;
            this.cView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.cView.CanFocus = true;
            this.cView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.cView.Data = "cView";
            this.cView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.cView.Title = "C";
            this.Add(this.cView);
            this.cTextView.Width = Dim.Percent(100);
            this.cTextView.Height = Dim.Percent(100);
            this.cTextView.X = 0;
            this.cTextView.Y = 0;
            this.cTextView.Visible = true;
            this.cTextView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.cTextView.CanFocus = true;
            this.cTextView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.cTextView.AllowsTab = true;
            this.cTextView.AllowsReturn = true;
            this.cTextView.WordWrap = false;
            this.cTextView.Data = "cTextView";
            this.cTextView.Text = "";
            this.cTextView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.cView.Add(this.cTextView);
            this.outputView.Width = Dim.Percent(33);
            this.outputView.Height = Dim.Percent(90);
            this.outputView.X = Pos.Percent(66);
            this.outputView.Y = 0;
            this.outputView.Visible = true;
            this.outputView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.outputView.CanFocus = true;
            this.outputView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.outputView.Data = "outputView";
            this.outputView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.outputView.Title = "Output";
            this.Add(this.outputView);
            this.askView.Width = Dim.Percent(33);
            this.askView.Height = Dim.Percent(10);
            this.askView.X = Pos.Percent(66);
            this.askView.Y = Pos.Percent(90);
            this.askView.Visible = true;
            this.askView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.askView.CanFocus = true;
            this.askView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.askView.Data = "askView";
            this.askView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.askView.Title = "Ask";
            this.Add(this.askView);
            this.askInput.Width = Dim.Percent(100);
            this.askInput.Height = 4;
            this.askInput.X = 0;
            this.askInput.Y = 0;
            this.askInput.Visible = true;
            this.askInput.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.askInput.CanFocus = true;
            this.askInput.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.askInput.AllowsTab = true;
            this.askInput.AllowsReturn = true;
            this.askInput.WordWrap = false;
            this.askInput.Data = "askInput";
            this.askInput.Text = "";
            this.askInput.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.askView.Add(this.askInput);
        }
    }
}
